version: '2.1'

services:
  db:
    image: postgis/postgis:12-3.1
    volumes:
      - ./Database/dbdata:/var/lib/postgresql
      - ./Database/scripts:/scripts
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - 25433:5432
